#-------------------------------------------- 
#------------ User Configuration ------------
#--------------------------------------------
substitutions:
  device_name: "melachaplug-cloudfree-p2"     # access web UI using "device_name".local/ or it's IP
  friendly_name: "Melacha Plug CloudFree P2"
  
  relay_1_gpio: "4"                  # Switch this section
  button_1_gpio:  "13"               # based on your chip
  built_in_led_gpio: "2"
  led_inverted: "true"

  restore_mode_relay:          "ALWAYS_OFF"  # relay state on startup
  restore_mode_led:            "ALWAYS_OFF"  # led state on startup
  restore_mode_button_switch:  "ALWAYS_OFF"  # switch which disables button state on startup

  timezone: America/New_York         # check format at en.wikipedia.org/wiki/List_of_tz_database_time_zones

  latitude: "40.669010"              # change to your location (important for proper zmanim)
  longitude: "-73.942871"            # 770 Chabad Lubavitch World Headquarters
  
  deg_shabbos_start:  "4"            # check a bit early just in case (shkiah is at -0.833)
  deg_shabbos_end:  "-8.5"           # time based off Alter Rebbe www.chabad.org/3209349
  deg_tzeit: "-6"

# Switch this section based on your chip
esp8266:
  board: esp01_1m
  restore_from_flash: true
# esp32:
#   board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid5
  password: !secret wifi_password5

esphome:
  includes:
    - header-files/melachaplug_main.h

packages:
  # Local Packages saved in plugins folder
  # melacha_config:      !include plugins/melachaplug/melacha_config.yaml     # Required
  # plug_info:           !include plugins/melachaplug/plug_info.yaml          # Required
  # location_info:       !include plugins/melachaplug/location_info.yaml      # Required
  # optional_config:     !include plugins/melachaplug/optional_config.yaml    # Optional

  remote_package:
    url: https://github.com/chabad-source/melachaplug/
    ref: main                                                               # optional
    files: 
      - esphome/plugins/melachaplug/melacha_config.yaml                     # Required
      - esphome/plugins/melachaplug/plug_info.yaml                          # Required
      - esphome/plugins/melachaplug/location_info.yaml                      # Required
      - esphome/plugins/melachaplug/optional_config.yaml                    # Optional
    refresh: 1d                                                             # Optional