#-------------------------------------------- 
#------------ User Configuration ------------
#--------------------------------------------
substitutions:
  device_name: "melachaplug-random-minute-s31"     # access web UI using "device_name".local/ or it's IP
  friendly_name: "Melacha Plug Random Minute S31"
  
  relay_1_gpio: "GPIO12"             # Switch this section
  button_1_gpio:  "GPIO0"            # based on your chip
  built_in_led_gpio: "GPIO13"
  led_inverted: "true"
  

  restore_mode_relay:          "ALWAYS_ON"  # relay state on startup
  restore_mode_led:            "ALWAYS_ON"  # led state on startup
  restore_mode_button_switch:  "ALWAYS_OFF" # switch which disables button state on startup

  timezone: America/New_York         # check format en.wikipedia.org/wiki/List_of_tz_database_time_zones

  latitude: "40.669010"              # change to your location (important for proper zmanim)
  longitude: "-73.942871"            # 770 Chabad Lubavitch World Headquarters
  
  deg_shabbos_start:  "4"            # check a bit early just in case (shkiah is at -0.833)
  deg_shabbos_end:  "-9"             # time based off Alter Rebbe www.chabad.org/3209349
  deg_tzeit: "-6"

# Switch this section based on your chip
esp8266:
  board: esp01_1m
  restore_from_flash: true
# esp32:
#   board: esp32doit-devkit-v1

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback"
    password: ""                     # password of fallback hotspot

#--------------------------------------------
#------------- Advanced Section -------------
#--------------------------------------------
#... add from melachaplug.yaml