#-------------------------------------------- 
#------------ User Configuration ------------
#--------------------------------------------
  substitutions:
    device_name: "melachaplug-cloudfree-p2"      # access web UI using http://melachaplug.local/ or it's IP
    friendly_name: "Melacha Plug CloudFree P2"
    
    relay_1_gpio: "4"              # Switch this section
    button_1_gpio:  "13"             # based on your chip
    built_in_led_gpio: "2"
    led_inverted: "true"
    
    deg_shabbos_start:  "4"         # check a bit early just in case (shkiah is at -0.833)
    deg_shabbos_end:  "-8.5"        # time based off Alter Rebbe https://www.chabad.org/3209349
    deg_tzeit: "-6"
  
    timezone: America/New_York      # check format https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  
    latitude: 40.66901°             # change to your location (important for proper zmanim)
    longitude: -73.94287°           # 770 Chabad Lubavitch World Headquarters
    manual_location: "false"          # change to true if you are setting the location above
  
  # Switch this section based on your chip
  esp8266:
    board: esp01_1m
    restore_from_flash: true
  # esp32:
  #   board: esp32doit-devkit-v1
  
  wifi:
    ssid: !secret wifi_ssid2
    password: !secret wifi_password2
  
    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ap:
      ssid: "${friendly_name} Fallback"
      password: ""                  # password of fallback hotspot
  
#--------------------------------------------
#------------- Advanced Section -------------
#--------------------------------------------
#... add from melachaplug.yaml
