#-------------------------------------------- 
#------------ User Configuration ------------
#--------------------------------------------
substitutions:
  device_name: "melachaplug-s31"     # access web UI using http://melachaplug-s31.local/ or it's IP
  friendly_name: "Melacha Plug S31"
  
  relay_1_gpio: "GPIO12"             # Switch this section
  button_1_gpio:  "GPIO0"            # based on your chip
  built_in_led_gpio: "GPIO13"
  led_inverted: "true"
  
  deg_shabbos_start:  "2"            # check a bit early just in case (shkiah is at -0.833)
  deg_shabbos_end:  "-9"             # time based off Alter Rebbe www.chabad.org/3209349 (added a bit extra)
  deg_tzeit: "-6"

  timezone: America/New_York         # check format https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

  latitude: "40.669010"              # change to your location (important for proper zmanim)
  longitude: "-73.942871"            # 770 Chabad Lubavitch World Headquarters

# Switch this section based on your chip
esp8266:
  board: esp01_1m
  restore_from_flash: true
# esp32:
#   board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid2
  password: !secret wifi_password2

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback"
    password: ""                  # password of fallback hotspot

#--------------------------------------------
#------------- Advanced Section -------------
#--------------------------------------------
#... add from melachaplug.yaml